PierresAuth/Models/Flavor.cs
using System.Collections.Generic;
using System;

namespace PierresAuth.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.Treats = new HashSet<FlavorTreat>();
    }
    public int FlavorId { get; set; }
    public string FlavorType { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<FlavorTreat> Treats { get; set; }
  }
}

PierresAuth/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using PierresAuth.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresAuth.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresAuthContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, PierresAuthContext db)
    {
      _db = db;
      _userManager = userManager;
    }
    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }
    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
      .Include(x => x.Treats)
      .ThenInclude(join => join.Treat)
      .FirstOrDefault(x => x.FlavorId == id);
      return View(thisFlavor);
    }
    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatType");
      return View();
    }
    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor, int TreatId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      if (TreatId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatType");
      return View(thisFlavor);
    }
    [HttpPost]
    public async Task<ActionResult> Edit(Flavor flavor, int TreatId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      if (TreatId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatType");
      return View(thisFlavor);
    }
    [HttpPost]
    public async Task<ActionResult> AddTreat(Flavor flavor, int TreatId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      if(TreatId != 0 )
      {
        _db.FlavorTreats.Add( new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }
    [HttpPost, ActionName("Delete")]
    public async Task<ActionResult> DeleteConfirmed(Flavor flavor, int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public async Task<ActionResult> DeleteTreat(Flavor flavor, int joinId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(x => x.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PierresAuth/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  @model PierresAuth.Models.Flavor
<h2>Add @Html.DisplayFor(model => model.FlavorType) Baked Good:</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select Baked Good")<br>
  @Html.DropDownList("TreatId")

  <br><br><input type="submit" value="Save" />
}
<br><p>@Html.ActionLink("Return to Flavor Profile List", "Index")</p>

</div>

PierresAuth/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  @model PierresAuth.Models.Flavor;
  <h2>Add Flavor Profile</h2>
  <hr />

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("FlavorType")<br>
    @Html.TextBoxFor(model => model.FlavorType)<br>

    <br><input type="submit" value="Save" />
  }
  <br><p>@Html.ActionLink("Return to Flavor List", "Index")</p>
</div>

PierresAuth/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  @model PierresAuth.Models.Flavor

  <h2>Are you sure you want to remove this flavor profile?</h2>
  <hr />
  <h4>Flavor Type: @Html.DisplayFor(model => model.FlavorType)</h4> <br>
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" /><br><br>
  }
  @Html.ActionLink("Flavor Profiles", "Index")
</div>

PierresAuth/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}
@model PierresAuth.Models.Flavor;
<div class="container">
  <h2>Today's @Html.DisplayFor(model => model.FlavorType) Offerings:</h2>
  <hr />
  
  @if (@Model.Treats.Count == 0)
  {
    <h4>There are no baked goods with this flavor profile.</h4>
  }
  else
  {
    <h4>Treats:</h4>
    <ul class="no-bullets">
      @foreach (var join in Model.Treats)
      {
        <li>@join.Treat.TreatType</li><br>
        @using (Html.BeginForm("DeleteTreat", "Flavors"))
        {
          @Html.Hidden("joinId", @join.FlavorTreatId)
          <input type="submit" value="Delete" /><br><br>
        }
      }
    </ul>
  }
  <br><p>@Html.ActionLink("Return to Flavor List", "Index")</p>
  <br><p>@Html.ActionLink("Update Flavor Profile", "Edit", new {id = Model.FlavorId})</p>
  <br><p>@Html.ActionLink("Remove Flavor Profile", "Delete", new {id = Model.FlavorId})</p>
  <br><p>@Html.ActionLink("Add Related Treats", "AddTreat", new {id = Model.FlavorId})</p>
  <br><p>@Html.ActionLink("Homepage", "Index", "Home")</p>
</div>

PierresAuth/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  @model PierresAuth.Models.Flavor;
  <h2>Edit Flavor Profile</h2>
  <hr />

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("FlavorType")<br>
    @Html.TextBoxFor(model => model.FlavorType)<br>

    <br><input type="submit" value="Save" />
  }
  <br><p>@Html.ActionLink("Return to Flavor List", "Index")</p>
</div>

PierresAuth/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  @using PierresAuth.Models;
  @model List<PierresAuth.Models.Flavor>
  <h1>Currently Offered Flavors</h1>
  <hr />
  @if (@Model.Count == 0)
  {
    <h3>Our flavors of the day have not been updated.</h3>
  }
  else
  {
    <ul class="no-bullets">
      @foreach (Flavor flavor in Model)
      {
        <li>@Html.ActionLink($"{flavor.FlavorType}", "Details", new { id = flavor.FlavorId })</li> <br>  
      }
    </ul>
  }
  <br><p>@Html.ActionLink("Add Flavor Profile", "Create")</p>
  <br><p>@Html.ActionLink("Homepage", "Index", "Home")</p>
</div>